<?php

return [

    /**
     * Base URL to use for all of Ziggy's route/URL generation.
     *
     * Uncomment to override globally - defaults to `url('/')`.
     */
    // 'url' => env('APP_URL'),

    /**
     * Path to the JavaScript file containing Ziggy’s routes and
     * configuration, generated by the ziggy:generate command.
     *
     * Uncomment this to change the default location - passing a path
     * directly to the command will still take priority.
     */
    'path' => 'resources/js/ziggy.js',

    'only' => [],

    'except' => [],

    'groups' => [],

    /**
     * Include a list of each route's middleware in Ziggy's output.
     *
     * Allowed values are true, false, or an array of middleware names.
     */
    'middleware' => false,

    /**
     * Don't include the JavaScript `route()` helper function
     * in the output of the `@routes` Blade directive.
     */
    'skip-route-function' => false,

];
