<?php

return [


    /**
     * Path to the JavaScript file containing Ziggy’s routes and
     * configuration, generated by the ziggy:generate command.
     *
     * Uncomment this to change the default location - passing a path
     * directly to the command will still take priority.
     */
    'path' => 'resources/js/ziggy.js',

    'only' => [],

    'except' => [],

    'groups' => [],

    'middleware' => false,

    'skip-route-function' => false,

];
