/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "posts.index": [],
    "postComments.store": [
        {
            "name": "post"
        }
    ]
}
}
export {};
